### ISSUE TITLE
SWMM LID component "Greenroof" type is missing！

### ISSUE THREAD

**Issue by s3886592** [Giswater/giswater#10]
When I use GISWater to build one SWMM model, I found "Green Roof" can't be modeled.

"GR" and "DRAINAGE MAT" is not included in the pulldown menu.

**Comment by xtorret** [comment]
"GR" and "DRAINAGE MAT" are not included in the pulldown menu because this options are options of SWMM 5.1. As we explain on the web site of Giswater, we are waiting to EPA finish the improving of SWMM 5.1 (more than 8 releases in last moths) in order to fully adapt Giswater to SWMM 5.1. On the other hand, you can insert this values using SQL: INSERT INTO "SCHEMA_NAME"."inp_value_lidcontrol" VALUES ('GR'); INSERT INTO "SCHEMA_NAME"."inp_value_lidcontrol" VALUES ('DRAINMAT');
