### ISSUE TITLE
Question on Z Values

### ISSUE THREAD

**Issue by tveinot** [Giswater/giswater#62]
This is a question not an issue.
In the Arc Catalog for the Water Network there are fields for z1 and z2 I was wondering where the value comes from; in the demo they are all set to 0.10. In the SWMM side those values are calculated by the database based on the y1 y2 and ymax values to get distance from node bottom to conduit bottom. Is it similar for the water?

**Comment by xtorret** [comment]
Hello Tyler.
z1 & z2 are related to the cross-section of conduit

**Comment by xtorret** [comment]
![imatge](https://user-images.githubusercontent.com/5804384/37801747-0b3d8380-2e28-11e8-9da8-a6f34622c077.png)

**Comment by xtorret** [comment]
z1 is the distance from the bottom of the trench to the bottom of the conduit (0.10 on the image)
z2 is the distance from the top of the conduit to the line of change of filling material (0.1 again on the image)
The issue is to calculate automaticly budgets about the cost of construction of the conduit, in combination with the parameters of the catalog of soils (cat_soil) and the catalog of pavements (cat_pavement)

**Comment by tveinot** [comment]
Thank you for the response; I apologize for my delay.
