### ISSUE TITLE
GIS Water 3 dev

### ISSUE THREAD

**Issue by tveinot** [Giswater/giswater#64]
Hello;
I have been experimenting with GISwater3 dev and found that my macrodma's and macrosectors disappear after drawing them, they are in the table through postgres but not the table view. I also have the same issue with waterwells. I filled everything in that was required, and went back and filled in information that is not. I used the ws_sample to find out what data those fields were looking for.
I checked the table view definition and the join there but couldn't find the issue, so I thought I would mention it here.
Thanks;
Tyler

**Comment by tveinot** [comment]
Apparently this had something to do with a table called selector_expl not having the values ID=1 expl_ID=31 cur_user=postgres I have to change my exploitation_id to 1 to get the features. Not sure what this table is for, the documentation is still in Spanish? I think?. Anyway; for every new exploitation do I have to enter a record for it in the selector_expl table ID=2 expl_id=2 cur_user=postgres also, if I move to another user will I have to add that user to this list for those exploitations?
Thanks;

**Comment by bbrzepka** [comment]
Hi Tyler,
The exploitation are the management areas, like for example municipalities. They allow users to work only with the zones they are interested in, without having all the data visible on the map. It's important to know that the elements in the main tables (node, arc,connec) have the information about the exploitation, but in qgis they are represented by the views (v_edit_node, v_edit_man_waterwell, etc.) and those views are filtered by the expl_id. In order to have visible the data, it's necessary to fill in the table selector_exploitation exactly as you did with the expl_id and user. Each user can see whatever he wishes for, so yes if you connect with another one you would have to fill it in with another user's name.
The same thing happens with states and sectors. In order to decide wherever you want to see elements on service/obsolete/planifieds you need to fill in the table selector_state and for the sectors you need to look for inp_selector_sector.
If you are also trying to work with qgis giswater 3 plugin there is an easy way to do that using buttons 'exploitation selector'- house icon, 'state selector' - check icon and for 'sector selector' - epa icon. The selector tables will be automatically filled in with the user with which you are connected to the database in qgis.

**Comment by tveinot** [comment]
WOW! Thank you; I pieced together parts of that through trial and error over the last few days but a full description is much more helpful. I tried translating bits and pieces of the documentation using  google but I think I missed some important paragraphs lol.
Thanks again;
Tyler

**Comment by tveinot** [comment]
Putting what you said into practice I managed to get the Exploitations and DMA's showing but the Macrosector and Sectors still disappear. I don't see a Sector Selector Tool and I tried to write the values directly into the linking table inp_selector_sector but I still don't have anything showing in my sectors view.

**Comment by tveinot** [comment]
Sorry, guess I should have waited longer for the refresh in QGIS; adding the data directly to the inp_selector_sector table seems to have done the trick. My sectors are also showing.
Thanks again!
Tyler
